import 'package:flutter/material.dart';

export 'richtrex_colorpicker_colors.dart' hide colors;

List<Color> colors = [
  Colors.pink,
  Colors.pinkAccent,
  Colors.red,
  Colors.redAccent,
  Colors.deepOrange,
  Colors.deepOrangeAccent,
  Colors.orange,
  Colors.orangeAccent,
  Colors.amber,
  Colors.amberAccent,
  Colors.yellow,
  Colors.yellowAccent,
  Colors.lime,
  Colors.limeAccent,
  Colors.lightGreen,
  Colors.lightGreenAccent,
  Colors.green,
  Colors.greenAccent,
  Colors.teal,
  Colors.tealAccent,
  Colors.cyan,
  Colors.cyanAccent,
  Colors.lightBlue,
  Colors.lightBlueAccent,
  Colors.blue,
  Colors.blueAccent,
  Colors.indigo,
  Colors.indigoAccent,
  Colors.purple,
  Colors.purpleAccent,
  Colors.deepPurple,
  Colors.deepPurpleAccent,
  Colors.blueGrey,
  Colors.brown,
  Colors.grey,
];
